---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-agent
  namespace: llama-agents-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-agent
  template:
    metadata:
      labels:
        app: secret-agent
    spec:
      initContainers:
        - name: init-message-queue
        - image: busybox:1.36
        - command:
            [
              "sh",
              "-c",
              "until nslookup message-queue.$(cat /var/run/secrets/kubernetes.io/serviceaccount/llama-agents-demo).svc.cluster.local; do echo waiting for message-queue; sleep 2; done",
            ]
      containers:
        - name: secret-agent
          env:
            - name: SECRET_AGENT_HOST
              valueFrom:
                configMapKeyRef:
                  name: xcore-config
                  key: SECRET_AGENT_HOST
            - name: SECRET_AGENT_PORT
              valueFrom:
                configMapKeyRef:
                  name: xcore-config
                  key: SECRET_AGENT_PORT
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: xcore-secret
                  key: OPENAI_API_KEY
          image: multi_agent_app:latest
          imagePullPolicy: Never
          command:
            [
              "uvicorn",
              "multi_agent_app.apps:secret_agent",
              "--host",
              "0.0.0.0",
              "--port",
              "8000",
              "--log-config",
              "./logging.ini",
              "--log-level",
              "debug",
            ]
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: secret-agent
  name: secret-agent
  namespace: llama-agents-demo
spec:
  selector:
    app: secret-agent
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secret-agent
  namespace: llama-agents-demo
spec:
  rules:
    - host: secret-agent.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: secret-agent
                port:
                  number: 8000
