version: "3"
services:
  message_queue:
    image: message_queue:latest
    command: uvicorn message_queue.app:app --host 0.0.0.0 --port 8000 --log-config ./logging.ini --log-level debug --reload
    # env_file:
    #   - ./contributor-1/.env.contributor.service
    ports:
      - "8000:8000"
    volumes:
      - ./message-queue/message_queue:/app/message_queue # load local code change to container without the need of rebuild
      - ./logging.ini:/app/logging.ini
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./message-queue/Dockerfile
      secrets:
        - id_ed25519
    healthcheck:
      test: wget --no-verbose --tries=1 http://0.0.0.0:8000/ || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  control_plane:
    image: control_plane:latest
    command: uvicorn control_plane.app:app --host 0.0.0.0 --port 8001 --log-config ./logging.ini --log-level debug --reload
    env_file:
      - ./control-plane/.env.control_plane.service
    ports:
      - "8001:8001"
    volumes:
      - ./control-plane/control_plane:/app/control_plane # load local code change to container without the need of rebuild
      - ./logging.ini:/app/logging.ini
    platform: linux/amd64
    depends_on:
      message_queue:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./control-plane/Dockerfile
      secrets:
        - id_ed25519
    healthcheck:
      test: wget --no-verbose --tries=1 http://0.0.0.0:8001/ || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  secret_agent:
    image: secret_agent:latest
    command: uvicorn secret_agent.app:app --host 0.0.0.0 --port 8002 --log-config ./logging.ini --log-level debug --reload --loop asyncio
    env_file:
      - ./secret-agent/.env.secret_agent.service
    ports:
      - "8002:8002"
    volumes:
      - ./secret-agent/secret_agent:/app/secret_agent # load local code change to container without the need of rebuild
      - ./logging.ini:/app/logging.ini
    platform: linux/amd64
    depends_on:
      message_queue:
        condition: service_healthy
      control_plane:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./secret-agent/Dockerfile
      secrets:
        - id_ed25519
    healthcheck:
      test: wget --no-verbose --tries=1 http://0.0.0.0:8002/ || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  funny_agent:
    image: funny_agent:latest
    command: uvicorn funny_agent.app:app --host 0.0.0.0 --port 8003 --log-config ./logging.ini --log-level debug --reload --loop asyncio
    env_file:
      - ./funny-agent/.env.funny_agent.service
    ports:
      - "8003:8003"
    volumes:
      - ./funny-agent/funny_agent:/app/funny_agent # load local code change to container without the need of rebuild
      - ./logging.ini:/app/logging.ini
    platform: linux/amd64
    depends_on:
      message_queue:
        condition: service_healthy
      control_plane:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./funny-agent/Dockerfile
      secrets:
        - id_ed25519
    healthcheck:
      test: wget --no-verbose --tries=1 http://0.0.0.0:8003/ || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
secrets:
  id_ed25519:
    file: ~/.ssh/id_ed25519
